import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from './components/Header';
import Nav from './components/Nav';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} bg-bgDarkBlue`}>
        <Header />
        <div className='relative mx-auto flex w-full max-w-screen-2xl tracking-wide'>
          <Nav />
          <main className='text-textLightBlue min-h-screen w-full overflow-auto px-3 pb-[40px] pt-24 transition-all duration-300 md:px-6'>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
